"use client";

import { createElement, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  Bell, Calendar, CalendarDays, CheckCircle, Compass, Eye, Heart, Home,
  MapPin, Menu, Package, Pencil, Plus, Search, SprayCan, Star,
  Tractor, Trash2, Truck, TrendingUp, Wrench, X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

type ListingStatus = "active" | "paused" | "rented";
type Filter = "all" | ListingStatus;
interface Listing { id: string; name: string; category: string; location: string; dailyPrice: number; status: ListingStatus; rating: number; totalRentals: number; createdAt: string; description?: string; }
interface ListingForm { name: string; category: string; location: string; dailyPrice: string; description: string; status: ListingStatus; }

const initialListings: Listing[] = [
  { id: "listing-001", name: "Trator John Deere 5075E", category: "Trator", location: "Marília, SP", dailyPrice: 850, status: "active", rating: 4.9, totalRentals: 18, createdAt: "2026-08-20", description: "Trator revisado e pronto para trabalhos no campo." },
  { id: "listing-002", name: "Pulverizador Agrícola Jacto", category: "Pulverizador", location: "Assis, SP", dailyPrice: 650, status: "rented", rating: 4.8, totalRentals: 12, createdAt: "2026-08-15", description: "Pulverizador com manutenção em dia." },
  { id: "listing-003", name: "Implemento Agrícola", category: "Implemento", location: "Ourinhos, SP", dailyPrice: 350, status: "active", rating: 4.7, totalRentals: 9, createdAt: "2026-08-10", description: "Implemento versátil para diferentes culturas." },
  { id: "listing-004", name: "Caminhonete S10", category: "Transporte", location: "Marília, SP", dailyPrice: 500, status: "paused", rating: 4.9, totalRentals: 7, createdAt: "2026-07-28", description: "Caminhonete utilitária para apoio à operação rural." },
];
const categories = ["Trator", "Colheitadeira", "Pulverizador", "Implemento", "Transporte", "Outro"];
const filters: { value: Filter; label: string }[] = [{ value: "all", label: "Todos" }, { value: "active", label: "Ativos" }, { value: "rented", label: "Alugados" }, { value: "paused", label: "Pausados" }];
const emptyForm: ListingForm = { name: "", category: "", location: "", dailyPrice: "", description: "", status: "active" };
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const iconForCategory = (category: string): LucideIcon => category === "Transporte" ? Truck : category === "Pulverizador" ? SprayCan : category === "Implemento" ? Wrench : Tractor;

export default function MeusAnunciosPage() {
  const router = useRouter();
  const [listings, setListings] = useState<Listing[]>(initialListings);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<Filter>("all");
  const [modal, setModal] = useState<"create" | "edit" | "delete" | "view" | null>(null);
  const [selected, setSelected] = useState<Listing | null>(null);
  const [form, setForm] = useState<ListingForm>(emptyForm);
  const [toast, setToast] = useState("");
  const summary = useMemo(() => ({ total: listings.length, active: listings.filter((item) => item.status === "active").length, rented: listings.filter((item) => item.status === "rented").length, paused: listings.filter((item) => item.status === "paused").length }), [listings]);
  const visibleListings = useMemo(() => { const term = query.trim().toLowerCase(); return listings.filter((item) => (!term || `${item.name} ${item.category} ${item.location}`.toLowerCase().includes(term)) && (filter === "all" || item.status === filter)); }, [filter, listings, query]);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2500); };
  const openCreate = () => { setForm(emptyForm); setSelected(null); setModal("create"); };
  const openEdit = (listing: Listing) => { setSelected(listing); setForm({ name: listing.name, category: listing.category, location: listing.location, dailyPrice: String(listing.dailyPrice), description: listing.description ?? "", status: listing.status }); setModal("edit"); };
  const updateForm = (field: keyof ListingForm, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const validForm = Boolean(form.name.trim() && form.category && form.location.trim() && Number(form.dailyPrice) > 0);
  const saveListing = () => { if (!validForm) return; const values = { name: form.name.trim(), category: form.category, location: form.location.trim(), dailyPrice: Number(form.dailyPrice), description: form.description.trim(), status: form.status }; if (selected) { setListings((current) => current.map((item) => item.id === selected.id ? { ...item, ...values } : item)); notify("Anúncio atualizado com sucesso!"); } else { setListings((current) => [{ ...values, id: `listing-${Date.now()}`, rating: 0, totalRentals: 0, createdAt: new Date().toISOString() }, ...current]); notify("Anúncio publicado com sucesso!"); } setModal(null); };
  const toggleStatus = (listing: Listing) => { const next: ListingStatus = listing.status === "paused" ? "active" : "paused"; setListings((current) => current.map((item) => item.id === listing.id ? { ...item, status: next } : item)); notify(next === "active" ? "Anúncio reativado com sucesso!" : "Anúncio pausado com sucesso!"); };
  const deleteListing = () => { if (!selected) return; setListings((current) => current.filter((item) => item.id !== selected.id)); setModal(null); notify("Anúncio excluído com sucesso!"); };

  return <main className="min-h-screen bg-background pb-28 text-foreground"><div className="mx-auto w-full max-w-6xl px-4 py-5 sm:px-6 lg:px-8">
    <header className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><button type="button" aria-label="Abrir menu" className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-klutch-teal shadow-sm"><Menu size={22} /></button><div><p className="font-display text-2xl font-bold tracking-tight text-klutch-teal">Meus anúncios</p><p className="text-sm text-klutch-muted">Gerencie seus equipamentos.</p></div></div><button type="button" aria-label="Abrir notificações" onClick={() => router.push("/notifications")} className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white text-klutch-teal shadow-sm"><Bell size={20} /></button></header>
    <section className="relative mt-6 overflow-hidden rounded-3xl bg-klutch-teal p-5 text-white shadow-[0_18px_35px_rgba(4,52,44,0.18)] sm:p-7"><div className="relative z-10"><p className="text-sm text-klutch-teal-accent">Visão geral</p><h1 className="mt-1 font-display text-2xl font-bold">Seu desempenho no Klutch</h1><p className="mt-1 text-sm text-white/70">Transforme máquinas ociosas em novas oportunidades.</p><div className="mt-6 grid grid-cols-3 gap-3 sm:max-w-xl"><Stat icon={Package} value={summary.total} label="anúncios" /><Stat icon={CheckCircle} value={summary.active} label="ativos" /><Stat icon={TrendingUp} value={summary.rented} label="alugados" /></div></div><div className="absolute -right-14 -top-16 h-52 w-52 rounded-full border-[26px] border-klutch-teal-light/30" /></section>
    <div className="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm text-klutch-muted">Você tem <strong className="text-klutch-teal">{summary.total} equipamentos</strong> cadastrados</p><h2 className="font-display text-xl font-bold text-klutch-teal">Seus equipamentos</h2></div><button type="button" onClick={openCreate} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-klutch-teal-light px-5 font-semibold text-white"><Plus size={19} /> Novo anúncio</button></div>
    <section className="mt-5"><label className="flex items-center gap-3 rounded-2xl border border-klutch-line bg-white px-4 py-3.5 shadow-sm focus-within:border-klutch-teal"><Search size={19} className="text-klutch-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Buscar equipamento" placeholder="Buscar equipamento..." className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-klutch-muted/70" />{query ? <button type="button" onClick={() => setQuery("")} aria-label="Limpar busca"><X size={17} /></button> : null}</label><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <button type="button" key={item.value} onClick={() => setFilter(item.value)} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-medium ${filter === item.value ? "bg-klutch-teal text-white" : "bg-white text-klutch-muted"}`}>{item.label}{item.value !== "all" ? <span className="ml-1.5 opacity-70">{summary[item.value]}</span> : null}</button>)}</div></section>
    {visibleListings.length ? <section className="mt-5 grid gap-4 md:grid-cols-2">{visibleListings.map((listing) => <ListingCard key={listing.id} listing={listing} onView={() => { setSelected(listing); setModal("view"); }} onEdit={() => openEdit(listing)} onDelete={() => { setSelected(listing); setModal("delete"); }} onToggle={() => toggleStatus(listing)} />)}</section> : <EmptyState onCreate={openCreate} hasListings={listings.length > 0} />}
  </div>{modal === "create" || modal === "edit" ? <ListingFormModal title={modal === "create" ? "Novo anúncio" : "Editar anúncio"} form={form} valid={validForm} onChange={updateForm} onClose={() => setModal(null)} onSave={saveListing} /> : null}{modal === "delete" ? <ConfirmModal onClose={() => setModal(null)} onConfirm={deleteListing} /> : null}{modal === "view" && selected ? <ViewModal listing={selected} onClose={() => setModal(null)} /> : null}{toast ? <div role="status" className="fixed bottom-24 left-1/2 z-50 -translate-x-1/2 rounded-full bg-klutch-teal px-5 py-3 text-center text-sm font-medium text-white shadow-lg">{toast}</div> : null}<BottomNavigation onCreate={openCreate} /></main>;
}

function Stat({ icon: Icon, value, label }: { icon: LucideIcon; value: number; label: string }) { return <div className="flex items-center gap-2"><Icon size={17} className="text-klutch-teal-accent" /><div><p className="font-display text-xl font-bold">{value}</p><p className="text-[11px] text-white/60">{label}</p></div></div>; }
function ListingCard({ listing, onView, onEdit, onDelete, onToggle }: { listing: Listing; onView: () => void; onEdit: () => void; onDelete: () => void; onToggle: () => void }) { const status = listing.status === "active" ? { label: "Ativo", style: "bg-klutch-teal-soft text-klutch-teal" } : listing.status === "rented" ? { label: "Alugado", style: "bg-klutch-amber-soft text-klutch-amber-dark" } : { label: "Pausado", style: "bg-[#efefeb] text-klutch-muted" }; return <article className="overflow-hidden rounded-3xl border border-klutch-line bg-white shadow-sm"><div className="relative flex h-32 items-center justify-center bg-gradient-to-br from-klutch-teal-soft to-[#f9f1dc] text-klutch-teal sm:h-40">{createElement(iconForCategory(listing.category), { size: 66, strokeWidth: 1.2 })}<span className={`absolute left-4 top-4 rounded-full px-3 py-1 text-xs font-semibold ${status.style}`}>{status.label}</span><button type="button" onClick={onView} aria-label={`Visualizar ${listing.name}`} className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full bg-white/90"><Eye size={17} /></button></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-display text-lg font-bold leading-tight text-klutch-teal">{listing.name}</h3><p className="mt-1 text-xs font-medium uppercase tracking-wider text-klutch-muted">{listing.category}</p></div><div className="flex shrink-0 gap-1"><button type="button" onClick={onEdit} aria-label={`Editar ${listing.name}`} className="flex h-9 w-9 items-center justify-center rounded-xl text-klutch-muted hover:bg-klutch-teal-soft"><Pencil size={16} /></button><button type="button" onClick={onDelete} aria-label={`Excluir ${listing.name}`} className="flex h-9 w-9 items-center justify-center rounded-xl text-klutch-muted hover:bg-red-50 hover:text-red-700"><Trash2 size={16} /></button></div></div><p className="mt-3 flex items-center gap-1.5 text-sm text-klutch-muted"><MapPin size={15} className="text-klutch-teal-light" />{listing.location}</p><div className="mt-4 flex items-end justify-between border-t border-klutch-line/60 pt-3"><div><span className="font-display text-xl font-bold text-klutch-teal">{money.format(listing.dailyPrice)}</span><span className="text-xs text-klutch-muted"> / dia</span></div><span className="flex items-center gap-1 text-sm font-medium text-klutch-amber-dark"><Star size={15} fill="currentColor" /> {listing.rating ? listing.rating.toFixed(1).replace(".", ",") : "Novo"}</span></div><div className="mt-3 flex items-center justify-between text-xs text-klutch-muted"><span className="flex items-center gap-1.5"><Calendar size={14} /> {listing.totalRentals} aluguéis realizados</span>{listing.status !== "rented" ? <button type="button" onClick={onToggle} className="font-semibold text-klutch-teal-light">{listing.status === "paused" ? "Reativar" : "Pausar"}</button> : null}</div></div></article>; }
function EmptyState({ onCreate, hasListings }: { onCreate: () => void; hasListings: boolean }) { return <section className="mt-5 rounded-3xl border border-dashed border-klutch-line bg-white px-6 py-12 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-klutch-teal-soft text-klutch-teal"><Package size={29} /></div><h2 className="mt-5 font-display text-xl font-bold text-klutch-teal">{hasListings ? "Nenhum anúncio encontrado" : "Comece a compartilhar seus equipamentos"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-klutch-muted">{hasListings ? "Tente ajustar sua busca ou selecionar outro filtro." : "Publique um equipamento e ajude outros produtores enquanto gera novas oportunidades."}</p><button type="button" onClick={onCreate} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-klutch-teal-light px-5 py-3 font-semibold text-white"><Plus size={18} /> {hasListings ? "Criar anúncio" : "Criar meu primeiro anúncio"}</button></section>; }
function ModalShell({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-40 flex items-end justify-center bg-klutch-teal/40 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div role="dialog" aria-modal="true" className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-lg sm:rounded-3xl sm:p-6"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold text-klutch-teal">{title}</h2><button type="button" onClick={onClose} aria-label="Fechar modal" className="flex h-9 w-9 items-center justify-center rounded-xl text-klutch-muted"><X size={19} /></button></div>{children}</div></div>; }
function ListingFormModal({ title, form, valid, onChange, onClose, onSave }: { title: string; form: ListingForm; valid: boolean; onChange: (field: keyof ListingForm, value: string) => void; onClose: () => void; onSave: () => void }) { const fields: [keyof ListingForm, string, string][] = [["name", "Nome do equipamento", "Ex.: Trator John Deere 5075E"], ["location", "Localização", "Ex.: Marília, SP"], ["dailyPrice", "Preço por dia", "Ex.: 850"]]; return <ModalShell title={title} onClose={onClose}><div className="mt-5 space-y-4">{fields.map(([field, label, placeholder]) => <label key={field} className="block text-sm font-medium text-klutch-teal">{label}<input required value={form[field]} onChange={(event) => onChange(field, event.target.value)} placeholder={placeholder} type={field === "dailyPrice" ? "number" : "text"} className="mt-1.5 w-full rounded-xl border border-klutch-line bg-[#fbfbf8] px-3.5 py-3 font-normal outline-none focus:border-klutch-teal" /></label>)}<label className="block text-sm font-medium text-klutch-teal">Categoria<select required value={form.category} onChange={(event) => onChange("category", event.target.value)} className="mt-1.5 w-full rounded-xl border border-klutch-line bg-[#fbfbf8] px-3.5 py-3 font-normal outline-none"><option value="">Selecione uma categoria</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="block text-sm font-medium text-klutch-teal">Descrição<textarea value={form.description} onChange={(event) => onChange("description", event.target.value)} rows={3} placeholder="Conte um pouco sobre o equipamento" className="mt-1.5 w-full resize-none rounded-xl border border-klutch-line bg-[#fbfbf8] px-3.5 py-3 font-normal outline-none" /></label>{title === "Editar anúncio" ? <label className="block text-sm font-medium text-klutch-teal">Status<select value={form.status} onChange={(event) => onChange("status", event.target.value)} className="mt-1.5 w-full rounded-xl border border-klutch-line bg-[#fbfbf8] px-3.5 py-3 font-normal outline-none"><option value="active">Ativo</option><option value="rented">Alugado</option><option value="paused">Pausado</option></select></label> : null}<button type="button" disabled={!valid} onClick={onSave} className="mt-2 flex w-full items-center justify-center gap-2 rounded-2xl bg-klutch-teal-light py-3.5 font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><CheckCircle size={18} /> {title === "Editar anúncio" ? "Salvar alterações" : "Publicar anúncio"}</button></div></ModalShell>; }
function ConfirmModal({ onClose, onConfirm }: { onClose: () => void; onConfirm: () => void }) { return <ModalShell title="Excluir anúncio?" onClose={onClose}><p className="mt-4 text-sm leading-6 text-klutch-muted">Esta ação removerá o equipamento dos seus anúncios.</p><div className="mt-6 flex gap-3"><button type="button" onClick={onClose} className="flex-1 rounded-2xl border border-klutch-line py-3 font-semibold text-klutch-teal">Cancelar</button><button type="button" onClick={onConfirm} className="flex-1 rounded-2xl bg-red-700 py-3 font-semibold text-white">Excluir anúncio</button></div></ModalShell>; }
function ViewModal({ listing, onClose }: { listing: Listing; onClose: () => void }) { return <ModalShell title="Detalhes do anúncio" onClose={onClose}><div className="mt-5 rounded-2xl bg-klutch-teal-soft p-5 text-center text-klutch-teal">{createElement(iconForCategory(listing.category), { className: "mx-auto", size: 54, strokeWidth: 1.3 })}<h3 className="mt-3 font-display text-xl font-bold">{listing.name}</h3><p className="mt-1 text-sm">{listing.description || "Equipamento disponível para a comunidade Klutch."}</p></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p className="rounded-xl bg-[#f7f7f3] p-3"><span className="block text-xs text-klutch-muted">Localização</span><strong>{listing.location}</strong></p><p className="rounded-xl bg-[#f7f7f3] p-3"><span className="block text-xs text-klutch-muted">Valor da diária</span><strong>{money.format(listing.dailyPrice)}</strong></p></div></ModalShell>; }
function BottomNavigation({ onCreate }: { onCreate: () => void }) { return <nav className="fixed inset-x-0 bottom-0 z-30 mx-auto flex h-[76px] max-w-[520px] items-center justify-around rounded-t-3xl bg-klutch-amber-soft px-3 pb-1 shadow-[0_-8px_25px_rgba(44,44,42,0.12)] sm:bottom-4 sm:rounded-full"><NavItem icon={Home} label="Início" /><NavItem icon={Compass} label="Explorar" /><button type="button" onClick={onCreate} aria-label="Criar anúncio" className="-translate-y-4 flex h-14 w-14 items-center justify-center rounded-full bg-klutch-teal text-white shadow-lg ring-4 ring-klutch-amber-soft"><Plus size={27} /></button><NavItem icon={CalendarDays} label="Aluguéis" /><NavItem icon={Heart} label="Favoritos" /></nav>; }
function NavItem({ icon: Icon, label }: { icon: LucideIcon; label: string }) { return <button type="button" className="flex min-w-14 flex-col items-center gap-1 text-[10px] font-medium text-klutch-amber-dark/75"><Icon size={19} /><span>{label}</span></button>; }
